const tempData = [
	{
		id: 0,
		chatUser: "김철수",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_default.png",
	},
	{
		id: 1,
		chatUser: "김수영",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test1.png",
	},
	{
		id: 2,
		chatUser: "이수혁",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test2.png",
	},
	{
		id: 3,
		chatUser: "곽철수",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 이 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test3.png",
	},
	{
		id: 4,
		chatUser: "박세훈",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test4.png",
	},
	{
		id: 5,
		chatUser: "박세훈",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test4.png",
	},
	{
		id: 6,
		chatUser: "박세훈",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test4.png",
	},
	{
		id: 7,
		chatUser: "박세훈",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 많이 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test4.png",
	},
	{
		id: 8,
		chatUser: "박세훈",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test4.png",
	},
	{
		id: 9,
		chatUser: "박세훈",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 많이 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test4.png",
	},
	{
		id: 10,
		chatUser: "박세훈",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 많이 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test4.png",
	},
	{
		id: 11,
		chatUser: "박세훈",
		totalMessage: "채팅했던 모든 내용 들어가기",
		lastMessage: "감사합니다 새해 복 받으세요!!",
		profileImg: "/img/profile_default.png",
		itemImg: "/img/item_test4.png",
	},
];

export default tempData;
